### PR TITLE
Fix package

### PR DESCRIPTION
**Pull request by syohex**
- Add package requirements header
- Use cl-lib functions instead of cl.el
- Update for newer helm
- Update for newer slime

### CODE REVIEW

**Comment by Ambrevar** [comment]
@thierryvolpiatto I've given this a quick shot and it seems to work.  Mind merging it?
If you are no longer maintaining the package, I'd be happy to take over! :)

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> @thierryvolpiatto I've given this a quick shot and it seems to
> work. Mind merging it?

Merging it where ?

> If you are no longer maintaining the package, I'd be happy to take over! :)

I think you can, the maintainer of this package was Michael Market, but
I don't think he is still maintaining it.
So if you want you can take over! (Perhaps ask him though?)

Thanks.

-- 
Thierry

**Comment by Ambrevar** [comment]
Oh, I assumed it was you because of the latest commit :p

I meant merging this pull request here.

@cofi Are you still maintaining this package?

**Comment by thierryvolpiatto** [comment]
Hoops! @syohex I am very sorry I mess this PR since 2016! please ping me privately if needed next time.
Merging now, sorry again.

**Pull request merged**
